server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhayangtao/spring_cloud_config/
          search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: #公共仓库不需要设置用户名、密码
          password:
          default-label: master # 设置分支
  profiles:
    active: dev # 设置环境