server:
  port: 8011
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service1:8761/eureka/,http://eureka-service2:8762/eureka/,http://eureka-service3:8763/eureka/
  instance:
    hostname: ribbon
    # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。
    # turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整