server:
  port: 8022
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix-stream
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service1:8761/eureka/,http://eureka-service2:8762/eureka/,http://eureka-service3:8763/eureka/
  instance:
    hostname: feign