server:
  port: 8022
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix-stream
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    hostname: feign