server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhayangtao/spring_cloud_config.git
          search-paths: config-repo
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/