server:
  port: 8012
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true